---
title: "Piramide Poblacional"
---

FUENTE: OBSERVATORIO DEMOGRÁFICO UNIVERSITARIO UNAH

Visita la página Web: https://datascience-machinelearning-solutions.github.io/homepage-ho.github.io/

```{r echo=FALSE}
knitr::opts_chunk$set(echo = F)

datacovid_observatorio<-fread("C:/Users/ladylee/Desktop/Shiny_r/BD Coronavirus 1jul21.csv",
                                      stringsAsFactors = TRUE )
```

Explorando datos
```{r  include=FALSE}
names(datacovid_observatorio) # Nombre de las Columnas
        
```

```{r  include=FALSE}
str(datacovid_observatorio) #Tipo de cada Variable del dataset
```

```{r  include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
class(datacovid_observatorio)    #Tipo de datos
dim(datacovid_observatorio)      #Número de columnas (variables) y filas (casos)
```
```{r  include=FALSE}
summary(datacovid_observatorio) #Resumen estadístico de cada Variable del dataset
```

```{r  echo=FALSE}
knitr::opts_chunk$set(echo = F)
 casos_covid_edades_muertes <- datacovid_observatorio %>% 
                dplyr::select(Departamento, Edad, `Tipo de Dato`) %>% 
                dplyr::filter(`Tipo de Dato`== "MUERTE") %>% 
                dplyr::filter(Edad <= 110 & Edad >=0) %>% 
                dplyr::mutate(rango=case_when(Edad %in%c(0:19)~ "0 a 19",
                                              Edad %in% c(20:39) ~ "20 a 39",
                                              Edad %in% c(40:59) ~ "40 a 59",
                                              Edad %in% c(60:79) ~ "60 a 79",
                                              Edad >=80 ~ "80+")) %>% 
                dplyr::group_by(Departamento, rango) %>% 
                dplyr::summarise(n=n()) %>% 
                dplyr::mutate(prop_prov = round((n/sum(n)*100),1)) %>% 
                #dplyr::filter(n>600) %>% 
                ungroup()
        
```
```{r  echo=FALSE}
knitr::opts_chunk$set(echo = F)
 casos_covid_edades_casos <- datacovid_observatorio %>% 
                dplyr::select(Departamento, Edad, `Tipo de Dato`) %>% 
                dplyr::filter(`Tipo de Dato`== "CASOS") %>% 
                dplyr::filter(Departamento %in% c("FM", "CORTÉS", "CHOLUTECA", "COMAYAGUA")) %>% 
                dplyr::filter(Edad <= 110 & Edad >=0) %>% 
# filtramos de una vez datos ruidosos. Establezco a priori 110 como edad #máxima
                dplyr::mutate(rango=case_when(Edad %in%c(0:19)~ "0 a 19",
                                              Edad %in% c(20:39) ~ "20 a 39",
                                              Edad %in% c(40:59) ~ "40 a 59",
                                              Edad %in% c(60:79) ~ "60 a 79",
                                              Edad >=80 ~ "80+")) %>% 
                dplyr::group_by(Departamento, rango) %>% 
  
                dplyr::summarise(n=n()) %>% 
                dplyr::mutate(prop_prov = round((n/sum(n)*100),1)) %>% 
                #dplyr::filter(n>600) %>% 
                ungroup()
        
```


```{r echo=FALSE}
knitr::opts_chunk$set(echo = F)
ggplot(casos_covid_edades_casos,
       aes(x=rango, y=prop_prov ))+
  geom_col(fill="blue")+
  labs(title = "Cantidad de casos por Departamento hasta el 1 de julio 2021",
       subtitle = "Distribución por rangos etáreos",
       caption = "Fuente: Observatorio Demgráfico Universitario UNAH",
       x= "Rango etáreo", y= "% de casos")+
  geom_text(aes(label = n),
            hjust = 0.5,
            vjust=-0.1,
            size=3)+
 
  facet_grid(facets = "Departamento")+
  theme_light()


```
```{r echo=FALSE}
knitr::opts_chunk$set(echo = F)

 casos_covid_edades_recu <- datacovid_observatorio %>% 
                dplyr::select(Departamento, Edad, `Tipo de Dato`) %>% 
                dplyr::filter(`Tipo de Dato`== "RECUPERADO") %>% 
                dplyr::filter(Departamento %in% c("FM", "CORTÉS", "CHOLUTECA", "COMAYAGUA")) %>% 
                dplyr::filter(Edad <= 110 & Edad >=0) %>% 

                dplyr::mutate(rango=case_when(Edad %in%c(0:19)~ "0 a 19",
                                              Edad %in% c(20:39) ~ "20 a 39",
                                              Edad %in% c(40:59) ~ "40 a 59",
                                              Edad %in% c(60:79) ~ "60 a 79",
                                              Edad >=80 ~ "80+")) %>% 
                dplyr::group_by(Departamento, rango) %>% 
  
                dplyr::summarise(n=n()) %>% 
                dplyr::mutate(prop_prov = round((n/sum(n)*100),1)) %>% 
                #dplyr::filter(n>600) %>% 
                ungroup()
        


```
```{r echo=FALSE}
knitr::opts_chunk$set(echo = F)

ggplot(casos_covid_edades_recu,
       aes(x=rango, y=prop_prov ))+
  geom_col(fill="green")+
  labs(title = "Cantidad de Recuperados por Departamento hasta el 1 de julio 2021",
       subtitle = "Distribución por rangos etáreos",
       caption = "Fuente: Observatorio Demgráfico Universitario UNAH",
       x= "Rango etáreo", y= "% de Recuperados")+
  geom_text(aes(label = n),
            hjust = 0.5,
            vjust=-0.1,
            size=3)+
 
  facet_grid(facets = "Departamento")+
  theme_light()


```


```{r echo=FALSE}
knitr::opts_chunk$set(echo = F)
##Cortés y Francisco Morazán
 casos_covid_edades_muertes_PRINC <- datacovid_observatorio %>% 
                dplyr::select(Departamento, Edad, `Tipo de Dato`) %>% 
                dplyr::filter(`Tipo de Dato`== "MUERTE") %>% 
                dplyr::filter(Departamento %in% c("FM", "CORTÉS", "CHOLUTECA", "COMAYAGUA")) %>% 
                dplyr::filter(Edad <= 110 & Edad >=0) %>% 
# filtramos de una vez datos ruidosos. Establezco a priori 110 como edad #máxima
                dplyr::mutate(rango=case_when(Edad %in%c(0:19)~ "0 a 19",
                                              Edad %in% c(20:39) ~ "20 a 39",
                                              Edad %in% c(40:59) ~ "40 a 59",
                                              Edad %in% c(60:79) ~ "60 a 79",
                                              Edad >=80 ~ "80+")) %>% 
                dplyr::group_by(Departamento, rango) %>% 
  
                dplyr::summarise(n=n()) %>% 
                dplyr::mutate(prop_prov = round((n/sum(n)*100),1)) %>% 
                #dplyr::filter(n>600) %>% 
                ungroup()
        
```

```{r echo=FALSE}
knitr::opts_chunk$set(echo = F)
ggplot(casos_covid_edades_muertes_PRINC,
       aes(x=rango, y=prop_prov ))+
  geom_col(fill="lightcoral")+
  labs(title = "Cantidad de fallecidos por Departamento hasta el 1 de julio 2021",
       subtitle = "Distribución por rangos etáreos", 
      
       x= "Rango etáreo", y= "% de fallecidos",  
       caption = "Fuente: Observatorio Demgráfico Universitario UNAH")+
  
  geom_text(aes(label = n),
            hjust = 0.5,
            vjust=-0.1,
            size=2.5)+
 
  facet_grid(facets = "Departamento")+
  theme_light()


```


```{r echo=FALSE}
knitr::opts_chunk$set(echo = F)
w<-datacovid_observatorio %>%  
  dplyr::filter(Departamento %in% c("FM", "CORTÉS", "CHOLUTECA", "COMAYAGUA")) %>%
  group_by(Departamento, `Tipo de Dato`) %>% 
  summarise(n=n()) %>% 
  mutate(prop=n/sum(n)*100) %>%
  ungroup() 
f<-data.frame(w)
```
```{r echo=FALSE}
knitr::opts_chunk$set(echo = F)

ggplot(f, aes(x=Departamento, y=prop, fill = Tipo.de.Dato))+
  geom_bar(stat="identity")+
  geom_text(aes(label = n),
            hjust = 0.5,
            vjust=-0.1,
            size=2.5)+
  scale_fill_manual(values=c("grey69", "red", "green")) +
  scale_y_log10()
# utilizamos la escala Logaritmica en el eje a los efectos de la visualización
```


```{r echo=FALSE}
knitr::opts_chunk$set(echo = F)
        

                A <- datacovid_observatorio  %>% 
                    dplyr::select(2,3,6) %>% 
                        
                filter(Sexo %in% c("Masculino", "Femenino")) %>%  
                droplevels() %>%
        
                  filter(`Tipo de Dato`== "MUERTE")%>% 
                  
                  filter(Edad <= 110 & Edad >=0) %>% 
                          dplyr::select(1,2) 
                  
                  
        

```



```{r echo=FALSE}
knitr::opts_chunk$set(echo = F)
library(epiDisplay)
pyramid(A$Edad,
                  A$Sexo,
                  binwidth = 5, decimal = 2,col.gender = c("gold", "red"),
                  main= "COVID-19: Fallecimiento por edad y sexo |  Honduras")
```


